sonar.projectKey=MediFollow-Frontend
sonar.projectName=MediFollow Frontend

sonar.sources=src

# ❌ on supprime les tests
# sonar.tests=src
# sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/*.spec.ts,**/node_modules/**

sonar.host.url=http://localhost:9000
sonar.login=YOUR_TOKEN

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info